import {useEffect,useRef,useState} from 'react';
import {api,ws} from '@appdeploy/client';
import {environmentLocalKey,environmentServerKey,IS_PRODUCTION,UMAY_ENVIRONMENT} from '../config/environment';
import {validateUmayBackup} from '../domain/backup';

export type UmaySetter<T>=(value:T|((current:T)=>T))=>void;
export const UMAY_DATA_ERROR_EVENT='umay:data-error';
export const UMAY_AUTH_CHANGED_EVENT='umay:auth-changed';
function reportDataError(operation:string,key:string){
 if(typeof window==='undefined')return;
 window.dispatchEvent(new CustomEvent(UMAY_DATA_ERROR_EVENT,{detail:{operation,key}}));
}
function readLocal<T>(localKey:string,seed:T):T{try{const raw=localStorage.getItem(localKey);return raw?JSON.parse(raw):seed}catch{return seed}}
function createRequestId(){return typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}

export function useUmayCollection<T>(serverKey:string,localKey:string,seed:T):[T,UmaySetter<T>]{
 serverKey=environmentServerKey(serverKey);localKey=environmentLocalKey(localKey);
 const initial=readLocal(localKey,seed),[state,setState]=useState<T>(initial),stateRef=useRef(initial),loaded=useRef(false),dirty=useRef(false),connectionId=useRef<string|null>(null),suppressSave=useRef(false),updatedAtRef=useRef<number|null>(null),writeQueue=useRef(Promise.resolve());
 const persist=async(value:T)=>{try{localStorage.setItem(localKey,JSON.stringify(value))}catch{}const response=await api.put('/api/data/'+encodeURIComponent(serverKey),{value,connection_id:connectionId.current,expectedUpdatedAt:updatedAtRef.current,requestId:createRequestId()});if(typeof response.data?.updatedAt==='number')updatedAtRef.current=response.data.updatedAt;try{localStorage.removeItem(`${localKey}.unsynced`)}catch{}return response};
 const enqueuePersist=(value:T)=>{dirty.current=true;writeQueue.current=writeQueue.current.catch(()=>undefined).then(()=>persist(value)).then(()=>{if(stateRef.current===value)dirty.current=false}).catch(()=>{try{localStorage.setItem(`${localKey}.unsynced`,JSON.stringify({savedAt:new Date().toISOString(),serverKey,value}))}catch{}reportDataError('conflict-or-save',serverKey)});};
 const update:UmaySetter<T>=(value)=>{setState(current=>{const next=typeof value==='function'?(value as (current:T)=>T)(current):value;stateRef.current=next;enqueuePersist(next);return next})};
 useEffect(()=>{let active=true;const conn=ws.connect();conn.onMessage(message=>{const p=message?.payload;if(p?.entity_type==='umay_data'&&p?.entity_id===serverKey&&active&&!dirty.current){api.get('/api/data/'+encodeURIComponent(serverKey)).then(response=>{if(!active||!response.data.found)return;suppressSave.current=true;updatedAtRef.current=typeof response.data.updatedAt==='number'?response.data.updatedAt:updatedAtRef.current;stateRef.current=response.data.value as T;setState(response.data.value as T);try{localStorage.setItem(localKey,JSON.stringify(response.data.value))}catch{}}).catch(()=>reportDataError('realtime-refresh',serverKey))}});conn.ready.then(async()=>{if(!active)return;connectionId.current=conn.connectionId;if(conn.connectionId)await api.post('/api/subscriptions',{entity_type:'umay_data',entity_id:serverKey,connection_id:conn.connectionId})}).catch(()=>{reportDataError('realtime',serverKey)});api.get('/api/data/'+encodeURIComponent(serverKey)).then(async response=>{if(!active)return;if(response.data.found&&typeof response.data.updatedAt==='number')updatedAtRef.current=response.data.updatedAt;if(dirty.current){enqueuePersist(stateRef.current)}else if(response.data.found){suppressSave.current=true;stateRef.current=response.data.value as T;setState(response.data.value as T);try{localStorage.setItem(localKey,JSON.stringify(response.data.value))}catch{}}else if(IS_PRODUCTION){reportDataError('missing-production-collection',serverKey)}else{enqueuePersist(stateRef.current)}loaded.current=true}).catch(()=>{loaded.current=true;reportDataError('load',serverKey)});return()=>{active=false;if(connectionId.current)api.post('/api/subscriptions/remove',{entity_type:'umay_data',entity_id:serverKey,connection_id:connectionId.current}).catch(()=>{});conn.disconnect()}},[serverKey,localKey]);
 useEffect(()=>{const reload=()=>{dirty.current=false;api.get('/api/data/'+encodeURIComponent(serverKey)).then(response=>{if(!response.data.found)return;suppressSave.current=true;updatedAtRef.current=typeof response.data.updatedAt==='number'?response.data.updatedAt:updatedAtRef.current;stateRef.current=response.data.value as T;setState(response.data.value as T);try{localStorage.setItem(localKey,JSON.stringify(response.data.value))}catch{}}).catch(()=>reportDataError('auth-refresh',serverKey))};window.addEventListener(UMAY_AUTH_CHANGED_EVENT,reload);return()=>window.removeEventListener(UMAY_AUTH_CHANGED_EVENT,reload)},[serverKey,localKey]);
 useEffect(()=>{const refresh=()=>{if(dirty.current)return;api.get('/api/data/'+encodeURIComponent(serverKey)).then(response=>{if(!response.data.found||dirty.current)return;suppressSave.current=true;updatedAtRef.current=typeof response.data.updatedAt==='number'?response.data.updatedAt:updatedAtRef.current;stateRef.current=response.data.value as T;setState(response.data.value as T);try{localStorage.setItem(localKey,JSON.stringify(response.data.value))}catch{}}).catch(()=>reportDataError('focus-refresh',serverKey))};const visible=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',visible)}},[serverKey,localKey]);
 useEffect(()=>{stateRef.current=state;try{localStorage.setItem(localKey,JSON.stringify(state))}catch{}if(!loaded.current)return;if(suppressSave.current){suppressSave.current=false;return}},[localKey,state]);
 return[state,update];
}

function downloadJson(value:unknown,filename:string){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
export function downloadLocalRecovery(){const records:Array<{key:string;value:unknown;unsynced?:unknown}>=[];for(let index=0;index<localStorage.length;index+=1){const key=localStorage.key(index);if(!key||!key.startsWith('umayv2.'))continue;try{const raw=localStorage.getItem(key);if(raw===null)continue;if(key.endsWith('.unsynced'))continue;const unsyncedRaw=localStorage.getItem(`${key}.unsynced`);records.push({key,value:JSON.parse(raw),unsynced:unsyncedRaw?JSON.parse(unsyncedRaw):undefined})}catch{}}downloadJson({schemaVersion:1,kind:'local-recovery',exportedAt:new Date().toISOString(),environment:UMAY_ENVIRONMENT,records},`UMAYv2-bu-cihaz-yerel-kurtarma-${new Date().toISOString().slice(0,10)}.json`);return records.length}
export async function downloadUmayData(){const response=await api.get('/api/data/export'),backup={...response.data,environment:UMAY_ENVIRONMENT};const validation=validateUmayBackup(backup);if(!validation.valid)throw new Error('Sunucudan alınan yedek doğrulanamadı: '+validation.errors.join(' '));downloadJson(backup,`UMAYv2-${UMAY_ENVIRONMENT}-veri-yedegi-${new Date().toISOString().slice(0,10)}.json`)}
