import { useEffect, useMemo, useState } from "react";
import { api } from "@appdeploy/client";
import { AlertTriangle, Check, ChevronDown, Copy, Filter, Plus, RotateCcw, Save, Target, Trash2 } from "lucide-react";
import { useUmayCollection } from "./services/umayData";
import type { UmayMembership } from "./domain/membership";

type Education={id:number;name:string;active:boolean};
type User={id:string;userId?:string;name:string;role:"Kurucu"|"Müdür"|"Danışman";branch:string;active:boolean};
type LegacyTargetLine={education:string;averageCoursePrice:number;courseTarget:number;coursesPerRegistration:number};
export type TargetPlan={id:string;name:string;start:string;end:string;scope:"Şube"|"Danışman";branch:string;assigneeId?:string;assigneeName?:string;parentPlanId?:string;totalCourseTarget?:number;targetCoursePrice?:number;downPaymentRate:number;collectionRate:number;status?:"Taslak"|"Aktif"|"Tamamlandı"|"Arşivlendi";lines?:LegacyTargetLine[];createdAt:string;createdBy:string;updatedAt?:string;updatedBy?:string};
type RegistrationRecord={id:string;student:string;date:string;education:string;advisor:string;source:string;paidCourses:number|null;revenue:number;downPayment:number;branch:string;status:string};
type Props={membership:UmayMembership;education:Education[];actual:{registrations:number;courses:number;revenue:number;downPayment:number;salesCollection:number|null;totalPeriodCollection:number|null;missingCourseRegistrations:number;records:RegistrationRecord[]};money:(n:number)=>string;notify:(s:string)=>void};

const isoMonth=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),last=new Date(y,d.getMonth()+1,0).getDate();return {start:`${y}-${m}-01`,end:`${y}-${m}-${last}`}};
const legacyCourses=(p?:TargetPlan)=>(p?.lines||[]).reduce((s,l)=>s+(Number(l.courseTarget)||0),0);
const legacyRevenue=(p?:TargetPlan)=>(p?.lines||[]).reduce((s,l)=>s+(Number(l.courseTarget)||0)*(Number(l.averageCoursePrice)||0),0);
const normalized=(p:TargetPlan):TargetPlan=>{const courses=Number(p.totalCourseTarget)||legacyCourses(p),revenue=legacyRevenue(p);return {...p,totalCourseTarget:courses,targetCoursePrice:Number(p.targetCoursePrice)||(courses?Math.round(revenue/courses):0)}};
export const planTotals=(p?:TargetPlan)=>{const n=p?normalized(p):undefined,courses=Number(n?.totalCourseTarget)||0,revenue=Math.round(courses*(Number(n?.targetCoursePrice)||0));return {courses,revenue,downPayment:Math.round(revenue*(Number(n?.downPaymentRate)||0)/100),collection:Math.round(revenue*(Number(n?.collectionRate)||0)/100)}};
const fresh=(membership:UmayMembership):TargetPlan=>{const range=isoMonth();return {id:"",name:"Aylık Hedef Planı",start:range.start,end:range.end,scope:"Şube",branch:membership.branch==="Tüm Şubeler"?"İzmit":membership.branch,totalCourseTarget:0,targetCoursePrice:0,downPaymentRate:30,collectionRate:55,status:"Taslak",createdAt:"",createdBy:membership.name}};

export default function TargetManagement({membership,actual,money,notify}:Props){
 const [plans,setPlans]=useUmayCollection<TargetPlan[]>("targetPlans","umayv2.targetPlans",[]);
 const [users,setUsers]=useState<User[]>([]);
 const [draft,setDraft]=useState<TargetPlan>(()=>fresh(membership));
 const [recordsOpen,setRecordsOpen]=useState(false),[allocations,setAllocations]=useState<Record<string,number>>({});
 const [recordFilters,setRecordFilters]=useState({branch:"",start:"",end:"",advisor:"",education:""});
 const canManage=membership.role==="Kurucu"||membership.role==="Müdür",canSetPrice=membership.role==="Kurucu";
 useEffect(()=>{if(canManage)api.get('/api/team/users').then(r=>setUsers(r.data.users||[])).catch(()=>setUsers([]))},[canManage,membership.branch]);
 useEffect(()=>{if(!draft.id||draft.scope!=="Şube"){setAllocations({});return}const next:Record<string,number>={};plans.filter(p=>p.parentPlanId===draft.id&&p.scope==="Danışman").forEach(p=>{if(p.assigneeId)next[p.assigneeId]=Number(p.totalCourseTarget)||0});setAllocations(next)},[draft.id,draft.scope,plans]);
 const visible=useMemo(()=>plans.filter(p=>membership.role==="Kurucu"||p.branch===membership.branch&&(p.scope==="Şube"||p.assigneeId===membership.userId)),[plans,membership]);
 const t=planTotals(draft),actualAverage=actual.courses>0?Math.round(actual.revenue/actual.courses):0;
 const recordFilterOptions=useMemo(()=>({
  branches:[...new Set(actual.records.map(r=>r.branch).filter(Boolean))].sort(),
  advisors:[...new Set(actual.records.map(r=>r.advisor).filter(v=>v&&v!=="—"))].sort(),
  educations:[...new Set(actual.records.map(r=>r.education).filter(v=>v&&v!=="—"))].sort()
 }),[actual.records]);
 const filteredRecords=useMemo(()=>actual.records.filter(r=>{
  const date=String(r.date||"").slice(0,10);
  return (!recordFilters.branch||r.branch===recordFilters.branch)
   &&(!recordFilters.start||date>=recordFilters.start)
   &&(!recordFilters.end||date<=recordFilters.end)
   &&(!recordFilters.advisor||r.advisor===recordFilters.advisor)
   &&(!recordFilters.education||r.education===recordFilters.education)
 }),[actual.records,recordFilters]);
 const filtersActive=Object.values(recordFilters).some(Boolean),clearRecordFilters=()=>setRecordFilters({branch:"",start:"",end:"",advisor:"",education:""});
 const newPlan=()=>setDraft(fresh(membership));
 const save=()=>{if(!draft.name.trim()||!draft.start||!draft.end||draft.start>draft.end){notify("Plan adı ve geçerli tarih aralığı zorunludur");return}if(draft.scope==="Danışman"&&!draft.assigneeId){notify("Danışman hedefi için danışman seçin");return}if(!(Number(draft.totalCourseTarget)>0)){notify("Toplam kur hedefini girin");return}if(!(Number(draft.targetCoursePrice)>0)){notify(canSetPrice?"Kurucunun hedef kur fiyatını girin":"Bu plan için kurucu hedef kur fiyatı tanımlamalıdır");return}const now=new Date().toISOString(),item:{[key:string]:unknown}={...draft,lines:undefined,id:draft.id||"HDF-"+Date.now(),createdAt:draft.createdAt||now,createdBy:draft.createdBy||membership.name,updatedAt:now,updatedBy:membership.name};setPlans(v=>draft.id?v.map(p=>p.id===draft.id?item as TargetPlan:p):[item as TargetPlan,...v]);setDraft(item as TargetPlan);notify(draft.id?"Hedef planı güncellendi":"Hedef planı kaydedildi")};
 const selectAssignee=(id:string)=>{const u=users.find(x=>(x.userId||x.id)===id);setDraft(d=>({...d,assigneeId:id,assigneeName:u?.name||"",branch:u?.branch||d.branch}))};
 const branchAdvisors=users.filter(u=>u.active&&u.role==="Danışman"&&u.branch===draft.branch),allocated=Object.values(allocations).reduce((s,n)=>s+(Number(n)||0),0),remaining=(Number(draft.totalCourseTarget)||0)-allocated;
 const saveAllocations=()=>{if(!draft.id||draft.scope!=="Şube"){notify("Önce şube hedef planını kaydedin");return}if(allocated>Number(draft.totalCourseTarget||0)){notify("Danışman hedefleri şube hedefini aşamaz");return}const now=new Date().toISOString(),ids=new Set(branchAdvisors.map(u=>u.userId||u.id));setPlans(current=>{const keep=current.filter(p=>p.parentPlanId!==draft.id||!p.assigneeId||!ids.has(p.assigneeId));const children=branchAdvisors.flatMap(u=>{const id=u.userId||u.id,courses=Number(allocations[id])||0;if(courses<=0)return[];const old=current.find(p=>p.parentPlanId===draft.id&&p.assigneeId===id);return[{...draft,id:old?.id||"HDF-D-"+Date.now()+"-"+id,scope:"Danışman" as const,assigneeId:id,assigneeName:u.name,parentPlanId:draft.id,totalCourseTarget:courses,createdAt:old?.createdAt||now,createdBy:old?.createdBy||membership.name,updatedAt:now,updatedBy:membership.name}]});return[...keep,...children]});notify(remaining===0?"Şube hedefi danışmanlara tamamen dağıtıldı":remaining+" kur henüz dağıtılmadı")};
 const metricCards=[["Kayıtlar",actual.registrations,null,"kayıt"],["Ücretli Kur",actual.courses,t.courses,"kur"],["Ciro",actual.revenue,t.revenue,"TL"],["Peşinat",actual.downPayment,t.downPayment,"TL"],["Yeni Kayıt Tahsilatı",actual.salesCollection,t.collection,"TL"],["Toplam Dönem Tahsilatı",actual.totalPeriodCollection,null,"TL"]] as const;
 return <div>
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-black/35">Planla · hesapla · izle</p><h1 className="text-[28px] font-semibold">Hedef Planlama</h1><p className="mt-1 max-w-2xl text-[11px] text-black/45">Toplam kur hedefini belirleyin; ciro, peşinat ve tahsilat hedefleri kurucunun hedef kur fiyatıyla otomatik hesaplansın.</p></div>{canManage&&<button onClick={newPlan} className="rounded-xl bg-black px-4 py-3 text-[11px] text-white"><Plus size={14} className="mr-2 inline"/>Yeni Hedef Planı</button>}</div>
  {actual.missingCourseRegistrations>0&&<div className="mt-5 flex items-start gap-3 rounded-[18px] border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle size={18}/><div><b className="text-[11px]">{actual.missingCourseRegistrations} kesinleşmiş kayıtta ücretli kur bilgisi eksik</b><p className="mt-1 text-[10px] opacity-70">Bu kayıtlar kur, ciro, peşinat ve ortalama kur fiyatı gerçekleşmesine dahil edilmedi. Kayıt kartında görünmeye devam eder.</p></div></div>}
  
  <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metricCards.map(([label,actualValue,target,unit])=>{const clickable=label==="Kayıtlar";return <article key={label} onClick={clickable?()=>setRecordsOpen(v=>!v):undefined} aria-expanded={clickable?recordsOpen:undefined} className={"rounded-[20px] border bg-white p-4 "+(clickable?"cursor-pointer transition hover:border-black hover:shadow-sm "+(recordsOpen?"border-black shadow-sm":""):"")}><p className="text-[9px] font-bold uppercase tracking-[.12em] text-black/35">{label}</p><div className="mt-3 flex items-end justify-between gap-2"><b className="text-[18px]">{actualValue===null?"Veri yok":unit==="TL"?money(actualValue):actualValue}</b><span className="text-right text-[9px] text-black/40">{target===null?unit:"/ "+(unit==="TL"?money(target):target+" "+unit)}</span></div>{target!==null&&actualValue!==null&&<div className="mt-3 h-1.5 rounded-full bg-black/5"><div className="h-full rounded-full bg-[#17191c]" style={{width:Math.min(100,target?actualValue/target*100:0)+"%"}}/></div>}{actualValue===null&&<p className="mt-2 text-[8px] leading-3 text-black/35">Fiilî ödeme hareketleri sisteme bağlandığında hesaplanacak.</p>}{clickable&&<p className="mt-2 flex items-center justify-between text-[8px] font-semibold text-black/55"><span>{recordsOpen?"Listeyi kapat":"Kayıtları filtrele ve incele"}</span><ChevronDown size={13} className={"transition "+(recordsOpen?"rotate-180":"")}/></p>}</article>})}</section>
  {recordsOpen&&<section className="mt-4 overflow-hidden rounded-[22px] border bg-white shadow-sm">
   <header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-[16px] font-semibold">Kesinleşmiş Kayıtlar</h2><p className="mt-1 text-[10px] text-black/45">{filteredRecords.length} / {actual.records.length} kayıt gösteriliyor · Filtreler birlikte uygulanır</p></div><button onClick={()=>setRecordsOpen(false)} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-[10px] font-semibold">Listeyi kapat<ChevronDown size={14} className="rotate-180"/></button></header>
   <div className="border-b bg-[#f7f8fa] p-4"><div className="mb-3 flex items-center justify-between"><span className="flex items-center gap-2 text-[10px] font-semibold"><Filter size={14}/>Filtreler</span>{filtersActive&&<button onClick={clearRecordFilters} className="flex items-center gap-1.5 text-[9px] font-semibold text-black/55 hover:text-black"><RotateCcw size={12}/>Tümünü temizle</button>}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
    <label><small className="mb-2 block text-[9px] font-bold uppercase tracking-[.04em] text-black/40">Şube</small><span className="relative block"><select value={recordFilters.branch} onChange={e=>setRecordFilters({...recordFilters,branch:e.target.value})} className="h-14 w-full appearance-none rounded-2xl border border-black/10 bg-white px-4 pr-11 text-[12px] font-medium text-black/75 outline-none transition hover:border-black/20 focus:border-black/40 focus:ring-4 focus:ring-black/[.05]"><option value="">Tüm şubeler</option>{recordFilterOptions.branches.map(v=><option key={v}>{v}</option>)}</select><ChevronDown aria-hidden="true" size={16} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-black/40"/></span></label>
    <label><small className="mb-2 block text-[9px] font-bold uppercase tracking-[.04em] text-black/40">Başlangıç tarihi</small><input type="date" value={recordFilters.start} onChange={e=>setRecordFilters({...recordFilters,start:e.target.value})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-[12px] font-medium text-black/75 outline-none transition hover:border-black/20 focus:border-black/40 focus:ring-4 focus:ring-black/[.05]"/></label>
    <label><small className="mb-2 block text-[9px] font-bold uppercase tracking-[.04em] text-black/40">Bitiş tarihi</small><input type="date" value={recordFilters.end} onChange={e=>setRecordFilters({...recordFilters,end:e.target.value})} className="h-14 w-full rounded-2xl border border-black/10 bg-white px-4 text-[12px] font-medium text-black/75 outline-none transition hover:border-black/20 focus:border-black/40 focus:ring-4 focus:ring-black/[.05]"/></label>
    <label><small className="mb-2 block text-[9px] font-bold uppercase tracking-[.04em] text-black/40">Danışman</small><span className="relative block"><select value={recordFilters.advisor} onChange={e=>setRecordFilters({...recordFilters,advisor:e.target.value})} className="h-14 w-full appearance-none rounded-2xl border border-black/10 bg-white px-4 pr-11 text-[12px] font-medium text-black/75 outline-none transition hover:border-black/20 focus:border-black/40 focus:ring-4 focus:ring-black/[.05]"><option value="">Tüm danışmanlar</option>{recordFilterOptions.advisors.map(v=><option key={v}>{v}</option>)}</select><ChevronDown aria-hidden="true" size={16} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-black/40"/></span></label>
    <label><small className="mb-2 block text-[9px] font-bold uppercase tracking-[.04em] text-black/40">Eğitim tipi</small><span className="relative block"><select value={recordFilters.education} onChange={e=>setRecordFilters({...recordFilters,education:e.target.value})} className="h-14 w-full appearance-none rounded-2xl border border-black/10 bg-white px-4 pr-11 text-[12px] font-medium text-black/75 outline-none transition hover:border-black/20 focus:border-black/40 focus:ring-4 focus:ring-black/[.05]"><option value="">Tüm eğitimler</option>{recordFilterOptions.educations.map(v=><option key={v}>{v}</option>)}</select><ChevronDown aria-hidden="true" size={16} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-black/40"/></span></label>
   </div>{recordFilters.start&&recordFilters.end&&recordFilters.start>recordFilters.end&&<p className="mt-2 text-[9px] font-semibold text-red-600">Başlangıç tarihi bitiş tarihinden sonra olamaz.</p>}</div>
   <div className="max-h-[520px] overflow-auto"><table className="w-full min-w-[1120px] text-left text-[10px]"><thead className="sticky top-0 z-10 bg-white text-black/45 shadow-[0_1px_0_rgba(0,0,0,.08)]"><tr>{["Öğrenci","Kayıt tarihi","Şube","Eğitim","Danışman","Kaynak","Ücretli kur","Ciro","Peşinat","Veri durumu"].map(h=><th key={h} className="px-4 py-3 font-bold uppercase">{h}</th>)}</tr></thead><tbody>{filteredRecords.map(r=><tr key={r.id} className="border-t hover:bg-black/[.02]"><td className="px-4 py-3 font-semibold">{r.student}</td><td className="px-4 py-3">{r.date}</td><td className="px-4 py-3">{r.branch||"—"}</td><td className="px-4 py-3">{r.education}</td><td className="px-4 py-3">{r.advisor}</td><td className="px-4 py-3"><span className={r.source==="Kaynak belirtilmemiş"?"text-amber-700":"font-medium"}>{r.source}</span></td><td className="px-4 py-3">{r.paidCourses===null?<span className="rounded-full bg-amber-100 px-2 py-1 text-amber-800">Eksik</span>:r.paidCourses}</td><td className="px-4 py-3">{money(r.revenue)}</td><td className="px-4 py-3">{money(r.downPayment)}</td><td className="px-4 py-3">{r.status}</td></tr>)}{filteredRecords.length===0&&<tr><td colSpan={10} className="p-10 text-center text-black/35">Seçili filtrelere uygun kesinleşmiş kayıt bulunamadı.</td></tr>}</tbody></table></div>
  </section>}
  <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><section className="rounded-[22px] border bg-white p-5">
   <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff200]"><Target size={18}/></span><div><h2 className="text-[15px] font-semibold">Plan Tanımı</h2><p className="text-[10px] text-black/40">Dönem, şube veya danışman ve tek ana satış hedefi</p></div></div>
   <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
    <label className="xl:col-span-2"><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Plan adı</small><input disabled={!canManage} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="w-full rounded-xl border p-3 text-[11px] disabled:bg-black/[.03]"/></label>
    <label><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Başlangıç</small><input disabled={!canManage} type="date" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})} className="w-full rounded-xl border p-3 text-[11px]"/></label>
    <label><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Bitiş</small><input disabled={!canManage} type="date" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})} className="w-full rounded-xl border p-3 text-[11px]"/></label>
    <label><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Plan durumu</small><select disabled={!canManage} value={draft.status||"Aktif"} onChange={e=>setDraft({...draft,status:e.target.value as TargetPlan["status"]})} className="w-full rounded-xl border bg-white p-3 text-[11px]"><option>Taslak</option><option>Aktif</option><option>Tamamlandı</option><option>Arşivlendi</option></select></label>
    <label><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Hedef türü</small><select disabled={!canManage||membership.role==="Müdür"} value={draft.scope} onChange={e=>setDraft({...draft,scope:e.target.value as TargetPlan["scope"],assigneeId:undefined,assigneeName:undefined})} className="w-full rounded-xl border bg-white p-3 text-[11px]"><option>Şube</option><option>Danışman</option></select></label>
    <label><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Şube</small><select disabled={!canManage||membership.role!=="Kurucu"||draft.scope==="Danışman"} value={draft.branch} onChange={e=>setDraft({...draft,branch:e.target.value})} className="w-full rounded-xl border bg-white p-3 text-[11px]"><option>İzmit</option><option>Körfez</option></select></label>
    {draft.scope==="Danışman"&&<label className="md:col-span-2"><small className="mb-1 block text-[9px] font-bold uppercase text-black/35">Danışman</small><select disabled={!canManage} value={draft.assigneeId||""} onChange={e=>selectAssignee(e.target.value)} className="w-full rounded-xl border bg-white p-3 text-[11px]"><option value="">Danışman seçin</option>{users.filter(u=>u.role==="Danışman").map(u=><option key={u.id} value={u.userId||u.id}>{u.name} · {u.branch}</option>)}</select></label>}
   </div>
   <div className="mt-6 grid gap-4 md:grid-cols-2">
    <label className="rounded-[18px] border p-4"><small className="block text-[9px] font-bold uppercase tracking-[.1em] text-black/35">Toplam kur hedefi</small><div className="mt-2 flex items-center gap-3"><input disabled={!canManage} type="number" min={0} value={draft.totalCourseTarget||""} onChange={e=>setDraft({...draft,totalCourseTarget:Math.max(0,Number(e.target.value))})} placeholder="Örn. 200" className="min-w-0 flex-1 rounded-xl border p-3 text-[18px] font-semibold"/><b className="text-[11px] text-black/40">KUR</b></div><p className="mt-2 text-[9px] text-black/40">Kayıt adedi hedef değildir; yalnızca gerçekleşen sonuç olarak izlenir.</p></label>
    <label className="rounded-[18px] border p-4"><small className="block text-[9px] font-bold uppercase tracking-[.1em] text-black/35">Kurucunun belirlediği hedef kur fiyatı</small><div className="mt-2 flex items-center gap-3"><input disabled={!canSetPrice} type="number" min={0} value={draft.targetCoursePrice||""} onChange={e=>setDraft({...draft,targetCoursePrice:Math.max(0,Number(e.target.value))})} placeholder="Örn. 25.000" className="min-w-0 flex-1 rounded-xl border p-3 text-[18px] font-semibold disabled:bg-black/[.04]"/><b className="text-[11px] text-black/40">TL</b></div><p className="mt-2 text-[9px] text-black/40">{canSetPrice?"Yönetim varsayımıdır; gerçekleşen satış ortalaması değildir.":"Yalnızca kurucu değiştirebilir."}</p></label>
   </div>
   <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="rounded-[16px] border bg-[#f7f8fa] p-4"><span className="flex justify-between text-[11px] font-semibold"><span>Peşinat oranı hedefi</span><b>%{draft.downPaymentRate}</b></span><input disabled={!canManage} type="range" min={0} max={100} value={draft.downPaymentRate} onChange={e=>setDraft({...draft,downPaymentRate:Number(e.target.value)})} className="mt-3 w-full"/></label><label className="rounded-[16px] border bg-[#f7f8fa] p-4"><span className="flex justify-between text-[11px] font-semibold"><span>Yeni kayıt tahsilat oranı hedefi</span><b>%{draft.collectionRate}</b></span><input disabled={!canManage} type="range" min={0} max={100} value={draft.collectionRate} onChange={e=>setDraft({...draft,collectionRate:Number(e.target.value)})} className="mt-3 w-full"/></label></div>
   {canManage&&<div className="mt-5 flex justify-end"><button onClick={save} className="rounded-xl bg-black px-5 py-3 text-[11px] text-white"><Save size={14} className="mr-2 inline"/>Hedef Planını Kaydet</button></div>}
   {canManage&&draft.id&&draft.scope==="Şube"&&<section className="mt-6 rounded-[20px] border bg-[#f7f8fa] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-[13px] font-semibold">Danışmanlara Kur Hedefi Dağıtımı</h3><p className="mt-1 text-[9px] text-black/40">Danışman toplamı şube hedefini aşamaz. Hedef fiyatı ve oranlar şube planından devralınır.</p></div><div className={"rounded-xl px-3 py-2 text-[10px] font-semibold "+(remaining<0?"bg-red-100 text-red-700":remaining===0?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-800")}>{remaining<0?Math.abs(remaining)+" kur fazla":remaining===0?"Tamamı dağıtıldı":remaining+" kur dağıtılmadı"}</div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{branchAdvisors.map(u=>{const id=u.userId||u.id;return <label key={id} className="flex items-center justify-between gap-3 rounded-xl border bg-white p-3"><span><b className="block text-[11px]">{u.name}</b><small className="text-[9px] text-black/35">{u.branch} · Aktif danışman</small></span><div className="flex items-center gap-2"><input type="number" min={0} value={allocations[id]||""} onChange={e=>setAllocations({...allocations,[id]:Math.max(0,Number(e.target.value))})} className="w-24 rounded-lg border p-2 text-right text-[12px] font-semibold"/><span className="text-[9px] text-black/40">KUR</span></div></label>})}{branchAdvisors.length===0&&<p className="md:col-span-2 rounded-xl border border-dashed p-5 text-center text-[10px] text-black/40">Bu şubede aktif danışman bulunmuyor.</p>}</div><div className="mt-4 flex justify-end"><button disabled={remaining<0||branchAdvisors.length===0} onClick={saveAllocations} className="rounded-xl bg-black px-4 py-3 text-[10px] text-white disabled:cursor-not-allowed disabled:opacity-30"><Save size={13} className="mr-2 inline"/>Dağılımı Kaydet</button></div></section>}
  </section>
  <aside className="space-y-4"><section className="rounded-[22px] bg-[#17191c] p-5 text-white"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-white/35">Otomatik hedef özeti</p><div className="mt-5 space-y-3">{[["Ücretli kur",t.courses+" kur"],["Hedef kur fiyatı",money(Number(draft.targetCoursePrice)||0)],["Ciro",money(t.revenue)],["Peşinat",money(t.downPayment)],["Yeni kayıt tahsilatı",money(t.collection)]].map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-white/10 pb-3 text-[11px]"><span className="text-white/45">{a}</span><b>{b}</b></div>)}</div><p className="mt-4 text-[9px] leading-5 text-white/45">Ciro = ücretli kur hedefi × kurucunun hedef kur fiyatı. Peşinat ve yeni kayıt tahsilatı hedefleri ciroya seçilen oranların uygulanmasıyla hesaplanır. Toplam dönem tahsilatı geçmiş taksitleri de içerdiğinden bu formülle üretilmez.</p></section>
   <section className="rounded-[22px] border bg-white p-4"><p className="text-[9px] font-bold uppercase text-black/35">Gerçekleşen satış göstergesi</p><div className="mt-3 flex items-end justify-between"><span className="text-[10px] text-black/45">Kesinleşmiş ortalama kur fiyatı</span><b className="text-[16px]">{money(actualAverage)}</b></div><p className="mt-2 text-[9px] leading-4 text-black/35">Kesinleşmiş ciro ÷ kesinleşmiş kur. Bekleyen ve alternatif teklifler dahil edilmez.</p></section>
   <section className="rounded-[22px] border bg-white p-4"><div className="flex items-center gap-2"><Check size={15}/><b className="text-[12px]">Kayıtlı planlar</b></div><div className="mt-3 space-y-2">{visible.length===0?<p className="rounded-xl bg-black/[.03] p-4 text-[10px] text-black/40">Henüz erişebileceğiniz bir hedef planı yok.</p>:visible.map(raw=>{const p=normalized(raw);return <button key={p.id} onClick={()=>setDraft(p)} className={"w-full rounded-xl border p-3 text-left "+(draft.id===p.id?"border-black bg-black/[.03]":"")}><b className="block text-[11px]">{p.name}</b><span className="mt-1 block text-[9px] text-black/40">{p.scope==="Danışman"?p.assigneeName:p.branch} · {p.start} / {p.end} · {p.status||"Aktif"}</span></button>})}</div>{draft.id&&<div className="mt-3 border-t pt-3"><p className="text-[9px] leading-4 text-black/40">Oluşturan: {draft.createdBy||"—"}<br/>Son güncelleyen: {draft.updatedBy||draft.createdBy||"—"}</p>{canManage&&<div className="mt-3 flex flex-wrap gap-3"><button onClick={()=>setDraft({...draft,id:"",name:draft.name+" · Kopya",status:"Taslak",createdAt:"",createdBy:membership.name})} className="flex items-center gap-2 text-[10px]"><Copy size={12}/>Kopyala</button><button onClick={()=>{setPlans(v=>v.filter(p=>p.id!==draft.id));newPlan();notify("Hedef planı silindi")}} className="flex items-center gap-2 text-[10px] text-red-600"><Trash2 size={12}/>Planı sil</button></div>}</div>}</section>
  </aside></div>
 </div>
}
